package com.practise;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.jdbcUtil.JdbcConnection;

public class StoredProcedureRetrievalApp {

	public static void main(String[] args) throws SQLException {
		Connection conn = null;
		CallableStatement cstmt = null;
		ResultSet rs = null;
		try {
			conn = JdbcConnection.getConnection();

			if (conn != null) {
				String storedProcedure = "{call getStudents(?)}";
				
				cstmt = conn.prepareCall(storedProcedure);
				
				if(cstmt!=null) {
					cstmt.setInt(1, 1);
					cstmt.execute();
					rs = cstmt.getResultSet();
					if(rs!=null) {
						if(rs.next()) {
							System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3));
							
						}
						else {
							System.out.println("No records found with sid as 1");
						}
					}
				}			

				
			}

		} catch (SQLException se) {
			se.printStackTrace();
		} finally {
			JdbcConnection.closeConnection(rs, cstmt, conn);
		}

	}

}
